### A demo/tutorial on the data structure for Species and SpeciesRegistry

**"Species"** is very broadly defined to be a molecule or larger entity that the simulator acts on.   
For now, small molecules, enzymes and macromolecules.   
NOT to be confused with ecological species (homo sapiens, etc)!

### TAGS :   "quick-start", "basic"

In [1]:
LAST_REVISED = "July 13, 2026"
LIFE123_VERSION = "1.0.0rc8"     # Library version this experiment is based on

In [2]:
#import set_path            # Using MyBinder?  Uncomment this before running the next cell!
                            # Importing this module will add the project's home directory to sys.path

In [3]:
#import sys, os
#os.getcwd()
#sys.path.append("C:/some_path/my_env_or_install")   # CHANGE to the folder containing your venv or libraries installation!
# NOTE: If any of the imports below can't find a module, uncomment the lines above, or try:  import set_path

from life123 import check_version, Species, SpeciesRegistry

In [4]:
check_version(LIFE123_VERSION)    # To check compatibility

OK

## 1. Individual species

In [5]:
# Minimal!
s1 = Species("A")   # The first, and only required, argument is a unique "id"

s1    # Notice the various attributes (fields); by default, "name" and "label" are made equal to the supplied "id"

Species(id='A', name='A', label='A', sort_order=0, diffusion_rate=None, charge=0, formula='', ec_number='', cas_number='', chebi='', locus_tag='', molecular_weight=None, categories=[], metadata={}, annotation='', plot_color='')

In [6]:
# Additional properties may be set at initialization...

s2 = Species(
            id="metK",
            name="methionine adenosyltransferase",
            categories=["protein", "enzyme"],
            molecular_weight=43000,
            ec_number="2.5.1.6",
            metadata={"compartment": "cytosol"},
            plot_color="darkturquoise"
        )

print(s2)

Species(id='metK', name='methionine adenosyltransferase', label='metK', sort_order=0, diffusion_rate=None, charge=0, formula='', ec_number='2.5.1.6', cas_number='', chebi='', locus_tag='', molecular_weight=43000, categories=['protein', 'enzyme'], metadata={'compartment': 'cytosol'}, annotation='', plot_color='darkturquoise')

In [7]:
# ... or added later

s2.diffusion_rate=123.   # s1 is a "Species" object (a python dataclass), and its attributes may be read/set the usual way

print(s2)

Species(id='metK', name='methionine adenosyltransferase', label='metK', sort_order=0, diffusion_rate=123.0, charge=0, formula='', ec_number='2.5.1.6', cas_number='', chebi='', locus_tag='', molecular_weight=43000, categories=['protein', 'enzyme'], metadata={'compartment': 'cytosol'}, annotation='', plot_color='darkturquoise')

In [8]:
print(s2.plot_color)

darkturquoise

In [9]:
# A number of validations are automatically performed

try:
    s2.diffusion_rate = -1       # Negative diffusion!
except Exception as ex:
    print("What were you thinking?!? ", ex)

What were you thinking?!?  `diffusion_rate` cannot be negative; the value given: -1

In [10]:
print(s2)       # Unchanged

Species(id='metK', name='methionine adenosyltransferase', label='metK', sort_order=0, diffusion_rate=123.0, charge=0, formula='', ec_number='2.5.1.6', cas_number='', chebi='', locus_tag='', molecular_weight=43000, categories=['protein', 'enzyme'], metadata={'compartment': 'cytosol'}, annotation='', plot_color='darkturquoise')

## 2. Registry of species
Keeping together all your species data

In [11]:
# Good for testing; auto-assigns id's, names and labels: "A", "B", "C", ....
test_registry = SpeciesRegistry(n_species=3)
test_registry

This is on object of type life123.species_registry.SpeciesRegistry
                 To display is, use the function as_recordset() or as_dataframe()
                 EXAMPLE:   my_species_registry.as_dataframe()

In [12]:
test_registry.as_dataframe()

,id,name,label,sort_order,diffusion_rate,charge,formula,ec_number,cas_number,chebi,locus_tag,molecular_weight,categories,metadata,annotation,plot_color
0,A,A,A,0,None,0,,,,,,None,[],{},,
1,B,B,B,1,None,0,,,,,,None,[],{},,
2,C,C,C,2,None,0,,,,,,None,[],{},,

In [13]:
# If you already have existing "Species" objects, you can initialize a SpeciesRegistry with them
sr = SpeciesRegistry(species=[s1,s2])
sr.as_recordset()

[{'id': 'A',
  'name': 'A',
  'label': 'A',
  'sort_order': 0,
  'diffusion_rate': None,
  'charge': 0,
  'formula': '',
  'ec_number': '',
  'cas_number': '',
  'chebi': '',
  'locus_tag': '',
  'molecular_weight': None,
  'categories': [],
  'metadata': {},
  'annotation': '',
  'plot_color': ''},
 {'id': 'metK',
  'name': 'methionine adenosyltransferase',
  'label': 'metK',
  'sort_order': 1,
  'diffusion_rate': 123.0,
  'charge': 0,
  'formula': '',
  'ec_number': '2.5.1.6',
  'cas_number': '',
  'chebi': '',
  'locus_tag': '',
  'molecular_weight': 43000,
  'categories': ['protein', 'enzyme'],
  'metadata': {'compartment': 'cytosol'},
  'annotation': '',
  'plot_color': 'darkturquoise'}]

In [14]:
sr.as_dataframe()

,id,name,label,sort_order,diffusion_rate,charge,formula,ec_number,cas_number,chebi,locus_tag,molecular_weight,categories,metadata,annotation,plot_color
0,A,A,A,0,NaN,0,,,,,,NaN,[],{},,
1,metK,methionine adenosyltransferase,metK,1,123.0,0,,2.5.1.6,,,,43000.0,"[protein, enzyme]",{'compartment': 'cytosol'},,darkturquoise

In [15]:
sr.number_of_species()

2

In [16]:
# Alternatively, you can start with an empty SpeciesRegistry, and then add Species later
sr_2 = SpeciesRegistry()
sr_2.as_recordset()

[]

In [17]:
sr_2.add_species("X")       # Minimal!

Species(id='X', name='X', label='X', sort_order=0, diffusion_rate=None, charge=0, formula='', ec_number='', cas_number='', chebi='', locus_tag='', molecular_weight=None, categories=[], metadata={}, annotation='', plot_color='')

In [18]:
sr_2.as_recordset()     # `name` and `label`, not directly supplied, were by default made equal to `id`

[{'id': 'X',
  'name': 'X',
  'label': 'X',
  'sort_order': 0,
  'diffusion_rate': None,
  'charge': 0,
  'formula': '',
  'ec_number': '',
  'cas_number': '',
  'chebi': '',
  'locus_tag': '',
  'molecular_weight': None,
  'categories': [],
  'metadata': {},
  'annotation': '',
  'plot_color': ''}]

In [19]:
sr_2.add_species("Y", annotation="need to re-test")

Species(id='Y', name='Y', label='Y', sort_order=1, diffusion_rate=None, charge=0, formula='', ec_number='', cas_number='', chebi='', locus_tag='', molecular_weight=None, categories=[], metadata={}, annotation='need to re-test', plot_color='')

In [20]:
# A SpeciesRegistry can also be started with lists/tuples of data
rome_cocktail = SpeciesRegistry(id=["S", "P", "Q", "R"], molecular_weight=[1200, 600, 2900, 1500], annotation=["Senatus",  "Populusque", None, "Romanus"])
rome_cocktail.as_dataframe()

,id,name,label,sort_order,diffusion_rate,charge,formula,ec_number,cas_number,chebi,locus_tag,molecular_weight,categories,metadata,annotation,plot_color
0,S,S,S,0,None,0,,,,,,1200,[],{},Senatus,
1,P,P,P,1,None,0,,,,,,600,[],{},Populusque,
2,Q,Q,Q,2,None,0,,,,,,2900,[],{},None,
3,R,R,R,3,None,0,,,,,,1500,[],{},Romanus,

In [21]:
# Several functions help deal with setting and reading values
rome_cocktail.update(species_id="Q", diffusion_rate=5, plot_color="red")

rome_cocktail.set_value(species_id="R", field="diffusion_rate", value=8)   # Alternate way to set a single value

rome_cocktail.as_dataframe()

,id,name,label,sort_order,diffusion_rate,charge,formula,ec_number,cas_number,chebi,locus_tag,molecular_weight,categories,metadata,annotation,plot_color
0,S,S,S,0,NaN,0,,,,,,1200,[],{},Senatus,
1,P,P,P,1,NaN,0,,,,,,600,[],{},Populusque,
2,Q,Q,Q,2,5.0,0,,,,,,2900,[],{},None,red
3,R,R,R,3,8.0,0,,,,,,1500,[],{},Romanus,

In [22]:
rome_cocktail.get_value(species_id="Q", field="molecular_weight")

2900

In [23]:
rome_cocktail.get_all_values(field="molecular_weight")

[1200, 600, 2900, 1500]

In [24]:
# Some search/aggregation functions
rome_cocktail.max_value(field="molecular_weight")

2900

In [25]:
rome_cocktail.has_missing_values(field="diffusion_rate")   # Some of the diffusion rates are indeed missing

True